{
  "formatVersion": "1.1",
  "component": {
    "group": "com.facebook.react",
    "module": "react-android",
    "version": "0.71.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "debugVariantDefaultApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat-resources",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.autofill",
          "module": "autofill",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.swiperefreshlayout",
          "module": "swiperefreshlayout",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.tracing",
          "module": "tracing",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.facebook.fbjni",
          "module": "fbjni",
          "version": {
            "requires": "0.3.0"
          }
        },
        {
          "group": "com.facebook.fresco",
          "module": "fresco",
          "version": {
            "requires": "2.5.0"
          },
          "excludes": [
            {
              "group": "com.facebook.fresco",
              "module": "soloader"
            },
            {
              "group": "com.facebook.fresco",
              "module": "nativeimagetranscoder"
            },
            {
              "group": "com.facebook.soloader",
              "module": "soloader"
            },
            {
              "group": "com.facebook.fresco",
              "module": "memory-type-native"
            },
            {
              "group": "com.facebook.fresco",
              "module": "imagepipeline-native"
            }
          ]
        },
        {
          "group": "com.facebook.fresco",
          "module": "imagepipeline-okhttp3",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "com.facebook.fresco",
          "module": "ui-common",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "com.facebook.infer.annotation",
          "module": "infer-annotation",
          "version": {
            "requires": "0.18.0"
          }
        },
        {
          "group": "com.facebook.soloader",
          "module": "soloader",
          "version": {
            "requires": "0.10.4"
          }
        },
        {
          "group": "com.facebook.yoga",
          "module": "proguard-annotations",
          "version": {
            "requires": "1.19.0"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp-urlconnection",
          "version": {
            "requires": "4.9.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.2"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "javax.inject",
          "module": "javax.inject",
          "version": {
            "requires": "1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "react-android-0.71.0-debug.aar",
          "url": "react-android-0.71.0-debug.aar",
          "size": 197782628,
          "sha512": "2eed181994cd6822cbdc7078a7ba9a034b4e5b2f6c5b48f4ccc5b84433c4faf3b741113e88e9265b1ad42d5fd3cbe03cd39b3d6df5201a983ee5ecd8fa8a372b",
          "sha256": "7e33e6db986eaf560cc208d92b710322b6f16d152bb68c2ad42bef72413045f3",
          "sha1": "c18c14dea1698c51fcae8244f20b9bf371eda39c",
          "md5": "2033a6894e1bd6f5e042621fca4d0f99"
        }
      ]
    },
    {
      "name": "debugVariantDefaultRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat-resources",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.autofill",
          "module": "autofill",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.swiperefreshlayout",
          "module": "swiperefreshlayout",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.tracing",
          "module": "tracing",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.facebook.fbjni",
          "module": "fbjni",
          "version": {
            "requires": "0.3.0"
          }
        },
        {
          "group": "com.facebook.fresco",
          "module": "fresco",
          "version": {
            "requires": "2.5.0"
          },
          "excludes": [
            {
              "group": "com.facebook.fresco",
              "module": "soloader"
            },
            {
              "group": "com.facebook.fresco",
              "module": "nativeimagetranscoder"
            },
            {
              "group": "com.facebook.soloader",
              "module": "soloader"
            },
            {
              "group": "com.facebook.fresco",
              "module": "memory-type-native"
            },
            {
              "group": "com.facebook.fresco",
              "module": "imagepipeline-native"
            }
          ]
        },
        {
          "group": "com.facebook.fresco",
          "module": "imagepipeline-okhttp3",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "com.facebook.fresco",
          "module": "ui-common",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "com.facebook.infer.annotation",
          "module": "infer-annotation",
          "version": {
            "requires": "0.18.0"
          }
        },
        {
          "group": "com.facebook.soloader",
          "module": "soloader",
          "version": {
            "requires": "0.10.4"
          }
        },
        {
          "group": "com.facebook.yoga",
          "module": "proguard-annotations",
          "version": {
            "requires": "1.19.0"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp-urlconnection",
          "version": {
            "requires": "4.9.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.2"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "javax.inject",
          "module": "javax.inject",
          "version": {
            "requires": "1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "react-android-0.71.0-debug.aar",
          "url": "react-android-0.71.0-debug.aar",
          "size": 197782628,
          "sha512": "2eed181994cd6822cbdc7078a7ba9a034b4e5b2f6c5b48f4ccc5b84433c4faf3b741113e88e9265b1ad42d5fd3cbe03cd39b3d6df5201a983ee5ecd8fa8a372b",
          "sha256": "7e33e6db986eaf560cc208d92b710322b6f16d152bb68c2ad42bef72413045f3",
          "sha1": "c18c14dea1698c51fcae8244f20b9bf371eda39c",
          "md5": "2033a6894e1bd6f5e042621fca4d0f99"
        }
      ]
    },
    {
      "name": "debugVariantDefaultSourcePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "react-android-0.71.0-debug-sources.jar",
          "url": "react-android-0.71.0-debug-sources.jar",
          "size": 1040888,
          "sha512": "0dfb280ed61369ba410486033c525f653bc4a3a242b9d560757d81177a5eb13ee95cf936549931480fb9d3635a65c1b4340eec17ef8be2a8269766d9e6fb230f",
          "sha256": "3015bbe4a4a2c23a6cc98edf215de8e45e7d54ddd29ff7907508b4efed2b1a2b",
          "sha1": "b0972a5ede46d563c1f3aaaac44be7c3d5a20df7",
          "md5": "2d131522fadb3179662a9bc468945461"
        }
      ]
    },
    {
      "name": "releaseVariantDefaultApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat-resources",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.autofill",
          "module": "autofill",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.swiperefreshlayout",
          "module": "swiperefreshlayout",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.tracing",
          "module": "tracing",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.facebook.fbjni",
          "module": "fbjni",
          "version": {
            "requires": "0.3.0"
          }
        },
        {
          "group": "com.facebook.fresco",
          "module": "fresco",
          "version": {
            "requires": "2.5.0"
          },
          "excludes": [
            {
              "group": "com.facebook.fresco",
              "module": "soloader"
            },
            {
              "group": "com.facebook.fresco",
              "module": "nativeimagetranscoder"
            },
            {
              "group": "com.facebook.soloader",
              "module": "soloader"
            },
            {
              "group": "com.facebook.fresco",
              "module": "memory-type-native"
            },
            {
              "group": "com.facebook.fresco",
              "module": "imagepipeline-native"
            }
          ]
        },
        {
          "group": "com.facebook.fresco",
          "module": "imagepipeline-okhttp3",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "com.facebook.fresco",
          "module": "ui-common",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "com.facebook.infer.annotation",
          "module": "infer-annotation",
          "version": {
            "requires": "0.18.0"
          }
        },
        {
          "group": "com.facebook.soloader",
          "module": "soloader",
          "version": {
            "requires": "0.10.4"
          }
        },
        {
          "group": "com.facebook.yoga",
          "module": "proguard-annotations",
          "version": {
            "requires": "1.19.0"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp-urlconnection",
          "version": {
            "requires": "4.9.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.2"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "javax.inject",
          "module": "javax.inject",
          "version": {
            "requires": "1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "react-android-0.71.0-release.aar",
          "url": "react-android-0.71.0-release.aar",
          "size": 91353969,
          "sha512": "12e22d6d097b89c385b2bc211028643a5f6f1f8b37eb1868773d4ef0c86341a6aa5a49babbda8ffd750c740a50cbc76c61bee5f131e83e04ad9411b4d7b23e70",
          "sha256": "fbafe66d7c01ef48f07138512e4b23a8c783145f7e1c68ba063f844e2b558a60",
          "sha1": "41af140157bb153dcdbb436c1df272b40d80ff59",
          "md5": "c9c30445d493bfb483f4dca78693fc1e"
        }
      ]
    },
    {
      "name": "releaseVariantDefaultRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat-resources",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.autofill",
          "module": "autofill",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.swiperefreshlayout",
          "module": "swiperefreshlayout",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.tracing",
          "module": "tracing",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.facebook.fbjni",
          "module": "fbjni",
          "version": {
            "requires": "0.3.0"
          }
        },
        {
          "group": "com.facebook.fresco",
          "module": "fresco",
          "version": {
            "requires": "2.5.0"
          },
          "excludes": [
            {
              "group": "com.facebook.fresco",
              "module": "soloader"
            },
            {
              "group": "com.facebook.fresco",
              "module": "nativeimagetranscoder"
            },
            {
              "group": "com.facebook.soloader",
              "module": "soloader"
            },
            {
              "group": "com.facebook.fresco",
              "module": "memory-type-native"
            },
            {
              "group": "com.facebook.fresco",
              "module": "imagepipeline-native"
            }
          ]
        },
        {
          "group": "com.facebook.fresco",
          "module": "imagepipeline-okhttp3",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "com.facebook.fresco",
          "module": "ui-common",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "com.facebook.infer.annotation",
          "module": "infer-annotation",
          "version": {
            "requires": "0.18.0"
          }
        },
        {
          "group": "com.facebook.soloader",
          "module": "soloader",
          "version": {
            "requires": "0.10.4"
          }
        },
        {
          "group": "com.facebook.yoga",
          "module": "proguard-annotations",
          "version": {
            "requires": "1.19.0"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp-urlconnection",
          "version": {
            "requires": "4.9.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.2"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "javax.inject",
          "module": "javax.inject",
          "version": {
            "requires": "1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "react-android-0.71.0-release.aar",
          "url": "react-android-0.71.0-release.aar",
          "size": 91353969,
          "sha512": "12e22d6d097b89c385b2bc211028643a5f6f1f8b37eb1868773d4ef0c86341a6aa5a49babbda8ffd750c740a50cbc76c61bee5f131e83e04ad9411b4d7b23e70",
          "sha256": "fbafe66d7c01ef48f07138512e4b23a8c783145f7e1c68ba063f844e2b558a60",
          "sha1": "41af140157bb153dcdbb436c1df272b40d80ff59",
          "md5": "c9c30445d493bfb483f4dca78693fc1e"
        }
      ]
    },
    {
      "name": "releaseVariantDefaultSourcePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "react-android-0.71.0-release-sources.jar",
          "url": "react-android-0.71.0-release-sources.jar",
          "size": 1040870,
          "sha512": "9456920a25321d0366bc48aab86907d85f18204b7d8e11858a03b5d2b3b2a1c174bdb71fd63beddce20f75987f5aa5e8aed11d71d3a860b7be86b6ed8f75f833",
          "sha256": "995abacedbf88189b977018b899779339ee464b054669ccc94d4df6995287553",
          "sha1": "5fdb21bea902176afb0eb85c2ef0340af3037ae2",
          "md5": "88a6c784507df16c39e840ebe35d9f11"
        }
      ]
    }
  ]
}
